/**
 * Style Dictionary Build Configuration (v5)
 * 
 * This script transforms design tokens from tokens/tokens.json into:
 * 1. CSS custom properties (src/styles/tokens.css)
 * 2. TypeScript module (src/tokens/index.ts)
 * 
 * Run: npm run build:tokens
 */

const { default: StyleDictionary } = require('style-dictionary');

// Register custom TypeScript format
StyleDictionary.registerFormat({
    name: 'typescript/module-declarations',
    format: ({ dictionary }) => {
        const header = `/**
 * DO NOT EDIT - This file is auto-generated by Style Dictionary
 * Source: tokens/tokens.json
 * 
 * To modify design tokens, edit tokens/tokens.json and run:
 * npm run build:tokens
 */\n\n`;

        // Convert token tree to nested object
        function buildTokenObject(obj) {
            const result = {};
            for (const key in obj) {
                if (obj[key].value !== undefined) {
                    result[key] = obj[key].value;
                } else {
                    result[key] = buildTokenObject(obj[key]);
                }
            }
            return result;
        }

        const tokens = buildTokenObject(dictionary.tokens);
        const tokensJson = JSON.stringify(tokens, null, 2);

        return header + `export const tokens = ${tokensJson} as const;\n\nexport type Tokens = typeof tokens;\n`;
    }
});

// Build configuration
const sd = new StyleDictionary({
    source: ['tokens/**/*.json'],
    platforms: {
        css: {
            transformGroup: 'css',
            buildPath: 'src/styles/',
            files: [
                {
                    destination: 'tokens.css',
                    format: 'css/variables',
                    options: {
                        outputReferences: false,
                        showFileHeader: true
                    }
                }
            ]
        },
        typescript: {
            transformGroup: 'js',
            buildPath: 'src/tokens/',
            files: [
                {
                    destination: 'index.ts',
                    format: 'typescript/module-declarations',
                    options: {
                        showFileHeader: false
                    }
                }
            ]
        }
    }
});

// Execute build
console.log('🎨 Building design tokens...\n');
sd.buildAllPlatforms();
console.log('\n✅ Design tokens built successfully!');
console.log('   - CSS: src/styles/tokens.css');
console.log('   - TypeScript: src/tokens/index.ts\n');
