export const LANGUAGE_LABELS: Record<string, string> = {
    abap: "ABAP",
    "actionscript-3": "ActionScript 3",
    ada: "Ada",
    adoc: "AsciiDoc",
    "angular-expression": "Angular Expression",
    "angular-html": "Angular HTML",
    "angular-inline-style": "Angular Inline Style",
    "angular-inline-template": "Angular Inline Template",
    "angular-let-declaration": "Angular Let Declaration",
    "angular-template": "Angular Template",
    "angular-template-blocks": "Angular Template Blocks",
    "angular-ts": "Angular TypeScript",
    apache: "Apache",
    apex: "Apex",
    apl: "APL",
    applescript: "AppleScript",
    ara: "Ara",
    asciidoc: "AsciiDoc",
    asm: "Assembly",
    astro: "Astro",
    awk: "Awk",
    ballerina: "Ballerina",
    bash: "Shell",
    bat: "Batch",
    batch: "Batch",
    be: "Berry",
    beancount: "Beancount",
    berry: "Berry",
    bibtex: "BibTeX",
    bicep: "Bicep",
    blade: "Blade",
    bsl: "BSL",
    c: "C",
    "c#": "C#",
    "c++": "C++",
    c3: "C3",
    cadence: "Cadence",
    cairo: "Cairo",
    cdc: "Cadence",
    cjs: "JavaScript",
    clarity: "Clarity",
    clj: "Clojure",
    clojure: "Clojure",
    cmake: "CMake",
    cobol: "COBOL",
    codeowners: "CODEOWNERS",
    codeql: "CodeQL",
    coffee: "CoffeeScript",
    coffeescript: "CoffeeScript",
    "common-lisp": "Common Lisp",
    coq: "Coq",
    cpp: "C++",
    "cpp-macro": "C++ Macro",
    cql: "Cypher",
    crystal: "Crystal",
    cs: "C#",
    csharp: "C#",
    css: "CSS",
    csv: "CSV",
    cue: "CUE",
    cypher: "Cypher",
    d: "D",
    dart: "Dart",
    dax: "DAX",
    desktop: "Desktop",
    diff: "Diff",
    docker: "Docker",
    dockerfile: "Docker",
    dotenv: "Dotenv",
    "dream-maker": "Dream Maker",
    edge: "Edge",
    elisp: "Emacs Lisp",
    elixir: "Elixir",
    elm: "Elm",
    "emacs-lisp": "Emacs Lisp",
    erb: "ERB",
    erl: "Erlang",
    erlang: "Erlang",
    f: "Fortran (Fixed Form)",
    "f#": "F#",
    f03: "Fortran (Free Form)",
    f08: "Fortran (Free Form)",
    f18: "Fortran (Free Form)",
    f77: "Fortran (Fixed Form)",
    f90: "Fortran (Free Form)",
    f95: "Fortran (Free Form)",
    fennel: "Fennel",
    fish: "Fish",
    fluent: "Fluent",
    for: "Fortran (Fixed Form)",
    "fortran-fixed-form": "Fortran (Fixed Form)",
    "fortran-free-form": "Fortran (Free Form)",
    fs: "F#",
    fsharp: "F#",
    ftl: "Fluent",
    gd: "GDScript",
    gdresource: "GDResource",
    gdscript: "GDScript",
    gdshader: "GDShader",
    genie: "Genie",
    gherkin: "Gherkin",
    "git-commit": "Git Commit",
    "git-rebase": "Git Rebase",
    gjs: "Glimmer JS",
    gleam: "Gleam",
    "glimmer-js": "Glimmer JS",
    "glimmer-ts": "Glimmer TS",
    glsl: "GLSL",
    gn: "GN",
    gnuplot: "Gnuplot",
    go: "Go",
    gql: "GraphQL",
    graphql: "GraphQL",
    groovy: "Groovy",
    gts: "Glimmer TS",
    hack: "Hack",
    haml: "Haml",
    handlebars: "Handlebars",
    haskell: "Haskell",
    haxe: "Haxe",
    hbs: "Handlebars",
    hcl: "HCL",
    hjson: "Hjson",
    hlsl: "HLSL",
    hs: "Haskell",
    html: "HTML",
    "html-derivative": "HTML Derivative",
    http: "HTTP",
    hurl: "Hurl",
    hxml: "HXML",
    hy: "Hy",
    imba: "Imba",
    ini: "INI",
    java: "Java",
    javascript: "JavaScript",
    jinja: "Jinja",
    "jinja-html": "Jinja HTML",
    jison: "Jison",
    jl: "Julia",
    js: "JavaScript",
    json: "JSON",
    json5: "JSON5",
    jsonc: "JSON with Comments",
    jsonl: "JSON Lines",
    jsonnet: "Jsonnet",
    jsx: "JSX",
    julia: "Julia",
    kdl: "KDL",
    kotlin: "Kotlin",
    kql: "Kusto",
    kts: "Kotlin",
    kusto: "Kusto",
    latex: "LaTeX",
    lean: "Lean",
    lean4: "Lean",
    less: "Less",
    liquid: "Liquid",
    lisp: "Common Lisp",
    llvm: "LLVM",
    log: "Log",
    logo: "Logo",
    lua: "Lua",
    luau: "Luau",
    make: "Makefile",
    makefile: "Makefile",
    markdown: "Markdown",
    marko: "Marko",
    matlab: "MATLAB",
    mbt: "MoonBit",
    mbti: "MoonBit",
    md: "Markdown",
    mdc: "MDC",
    mdx: "MDX",
    mermaid: "Mermaid",
    mips: "MIPS Assembly",
    mipsasm: "MIPS Assembly",
    mjs: "JavaScript",
    mmd: "Mermaid",
    mojo: "Mojo",
    moonbit: "MoonBit",
    move: "Move",
    nar: "Narrat",
    narrat: "Narrat",
    nextflow: "Nextflow",
    nf: "Nextflow",
    nginx: "Nginx",
    nim: "Nim",
    nix: "Nix",
    nu: "Nushell",
    nushell: "Nushell",
    objc: "Objective-C",
    "objective-c": "Objective-C",
    "objective-cpp": "Objective-C++",
    ocaml: "OCaml",
    odin: "Odin",
    openscad: "OpenSCAD",
    pascal: "Pascal",
    perl: "Perl",
    perl6: "Raku",
    php: "PHP",
    pkl: "Pkl",
    plsql: "PL/SQL",
    po: "PO",
    polar: "Polar",
    postcss: "PostCSS",
    pot: "PO",
    potx: "PO",
    powerquery: "Power Query",
    powershell: "PowerShell",
    prisma: "Prisma",
    prolog: "Prolog",
    properties: "Properties",
    proto: "Protocol Buffers",
    protobuf: "Protocol Buffers",
    ps: "PowerShell",
    ps1: "PowerShell",
    pug: "Pug",
    puppet: "Puppet",
    purescript: "PureScript",
    py: "Python",
    python: "Python",
    ql: "CodeQL",
    qml: "QML",
    qmldir: "QML Dir",
    qss: "QSS",
    r: "R",
    racket: "Racket",
    raku: "Raku",
    razor: "Razor",
    rb: "Ruby",
    reg: "Reg",
    regex: "RegExp",
    regexp: "RegExp",
    rel: "Rel",
    riscv: "RISC-V",
    ron: "RON",
    rosmsg: "ROS Message",
    rst: "reStructuredText",
    ruby: "Ruby",
    rust: "Rust",
    sas: "SAS",
    sass: "Sass",
    scad: "OpenSCAD",
    scala: "Scala",
    scheme: "Scheme",
    scss: "SCSS",
    sh: "Shell",
    shaderlab: "ShaderLab",
    shell: "Shell",
    shellscript: "Shell",
    smalltalk: "Smalltalk",
    soy: "Soy",
    sparql: "SPARQL",
    spl: "Splunk",
    splunk: "Splunk",
    sql: "SQL",
    stata: "Stata",
    styl: "Stylus",
    stylus: "Stylus",
    surql: "SurrealQL",
    surrealql: "SurrealQL",
    svelte: "Svelte",
    swift: "Swift",
    "system-verilog": "SystemVerilog",
    systemd: "systemd",
    talon: "TalonScript",
    talonscript: "TalonScript",
    tasl: "TASL",
    tcl: "Tcl",
    templ: "Templ",
    terraform: "Terraform",
    tex: "TeX",
    tf: "Terraform",
    tfvars: "Terraform Variables",
    toml: "TOML",
    tres: "GDResource",
    ts: "TypeScript",
    tscn: "GDResource",
    tsp: "TypeSpec",
    tsv: "TSV",
    tsx: "TSX",
    turtle: "Turtle",
    twig: "Twig",
    typ: "Typst",
    typescript: "TypeScript",
    typespec: "TypeSpec",
    typst: "Typst",
    v: "V",
    vala: "Vala",
    vb: "VB",
    verilog: "Verilog",
    vhdl: "VHDL",
    viml: "VimL",
    vimscript: "VimL",
    vue: "Vue",
    vy: "Vyper",
    vyper: "Vyper",
    wasm: "WebAssembly",
    wenyan: "Wenyan",
    wgsl: "WGSL",
    wiki: "Wikitext",
    wikitext: "Wikitext",
    wit: "WIT",
    wl: "Wolfram",
    wolfram: "Wolfram",
    xml: "XML",
    xsl: "XSL",
    yaml: "YAML",
    yml: "YAML",
    zenscript: "ZenScript",
    zig: "Zig",
    zsh: "Shell",
};

export const formatLanguageLabel = (language: string): string => {
    return LANGUAGE_LABELS[language] ?? language;
};
