/**
 * DO NOT EDIT - This file is auto-generated by Style Dictionary
 * Source: tokens/tokens.json
 * 
 * To modify design tokens, edit tokens/tokens.json and run:
 * npm run build:tokens
 */

export const tokens = {
  "color": {
    "background": {
      "light": "#f0f0f0",
      "dark": "#1a1a1a"
    },
    "text": {
      "first": {
        "light": "#000000",
        "dark": "#ffffff"
      },
      "second": {
        "light": "#333333",
        "dark": "#e5e5e5"
      },
      "third": {
        "light": "#666666",
        "dark": "#9e9e9e"
      }
    },
    "accent": {
      "light": "#ff8c00",
      "dark": "#ffa500"
    }
  },
  "font": {
    "family": {
      "sans": "Inter, ui-sans-serif, system-ui, sans-serif"
    }
  }
} as const;

export type Tokens = typeof tokens;
